### ISSUE TITLE
Translate "phone number" placeholder in SMS message preview

### ISSUE THREAD

**Issue by smcmurtry** [cds-snc/notification-api#846] opened 2020-05-08 19:53 UTC
<img width="700" alt="Screen Shot 2020-05-08 at 11 39 11 AM" src="https://user-images.githubusercontent.com/5498428/81443720-2b0f3d00-9133-11ea-9828-7ffc68052864.png">

**Comment by AntoineAugusti** [comment] 2020-09-22 15:22
Duplicate of #850

**Closed by AntoineAugusti** 2020-09-22 15:22 UTC
Labels: French 🇫🇷, bug:bug:
