### ISSUE TITLE
Rework senders csv upload/recipient page

### ISSUE THREAD

**Issue by willeybryan** [cds-snc/notification-api#808] opened 2020-04-29 17:42 UTC
**Story**
When sending a notification to users I want to be able to easily send to a list of users without getting confused. 

**What?**
- The page should include a clear path for the user to send to multiple recipients

**Why?**
- Senders get confused and don't know how to upload a spreadsheet, or they just want to send to a couple people. 

**Done When**
- Peer reviewed designs with accessibility and French are shared with the team for feedback and integration
- Stretch Goal: Depending on size of feedback, integrate feedback into design.

**notes**
https://trello.com/c/OUzttjbL/88-1-rework-recipients-page-s

**Comment by ClementineHahn** [comment] 2020-05-01 14:27
After exploration meeting will happen May 1st with dev to explore feasibility and sizing of different options envisioned by design on this card.
Triggered the need for a recurrent dev-design sync to continue explore sizing and feasibilities

**Comment by ClementineHahn** [comment] 2020-05-07 14:20
Issue is actually too big, need to refine the scope to make it more realistic. It was defined by page and its actually not realistic, should be broken up by flow. 
More detail to come soon thanks to @anikbrazeau and @ioanacontu feeback in order to clarify the new "done when"

**Comment by anikbrazeau** [comment] 2020-05-11 14:13
https://docs.google.com/spreadsheets/d/1l2BmmGMTn8an6uaElob8adXV-x-gelhxsNmd09lX2u0/edit#gid=2075894813

**Comment by ClementineHahn** [comment] 2020-05-13 19:06
Done when is : when new card is created to actually implement new design proposal, card would have been prepped with dev feedback with sizing and all needed artefacts. 
New card should be linked to this one in order to close the issue.

**Comment by anikbrazeau** [comment] 2020-05-21 16:25
Updated Figma link reorganized by pages: 

https://www.figma.com/file/fRVRKm7cM8MUuBWUJbrfgU/Senders-(content-creators-%2F-service-operators)?node-id=1430%3A0

**Closed** 2020-07-21 18:04 UTC
Labels: Ideate
